alias cxx="clang++ -Wall -Wextra -Wpedantic -std=c++17 -g -ggdb3 -O0 -fsanitize=address,undefined -fno-omit-frame-pointer -o main"
alias c="cxx main.cpp"
alias r="./main"
alias cr="c && r"
alias d="gdb ./main"
